{{- if .Values.backup.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borealis-backup
  labels:
    application: borealis-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      application: borealis-backup
  template:
    metadata:
      labels:
        application: borealis-backup
    spec:
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: {{.Values.backup.storageName}}
      containers:
        - name: borealis-backup-leader
          imagePullPolicy: IfNotPresent
          image: chrislusf/seaweedfs:latest
          args:
            - server -filer -dir=/backups -s3 -volume.max={{.Values.backup.storageVolumes}}
          ports:
            - containerPort: {{.Values.backup.port}}
          volumeMounts:
            - mountPath: "/backups"
              name: backup-volume
            - mountPath: "/data"
              name: backup-volume
{{- end }}