{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backup.serviceName}}
  labels:
    application: {{.Values.backup.serviceName}}
spec:
  type: ClusterIP
  ports:
    - name: backup
      port: {{ .Values.backup.port }}
      targetPort: {{ .Values.backup.port }}
  selector:
    application: borealis-backup
{{- end }}