apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    application: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
    - name: grpc
      port: {{ include "load.internal.grpcProxyPort" . }}
      targetPort: {{ include "load.internal.grpcProxyPort" . }}
    - name: prometheus
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
  selector:
    application: borealis-infrastructures

