apiVersion: v1
kind: Service
metadata:
  name: borealis-operator-service
  labels:
    application: borealis-operator-service
spec:
  type: ClusterIP
  ports:
    - name: operator
      port: {{ .Values.operator.config.api_port }}
      targetPort: {{ .Values.operator.config.api_port }}
  selector:
    application: borealis-operator

