environment: kubernetes
host: "" # Put your host here (Required). Ex: https://mycompany.com
rootUrlPath: /borealis # Sub path, so it won't conflict with your other ingress routes (Required). Ex: /borealis
globalTlsStrategy: noop
imageName: public.ecr.aws/borealisdb/console
imageVersion: latest
dataRetentionDays: 30 # This is the data retention of the time series storage (Clickhouse, Victoriametrics)
secretName: borealis-secrets # Name of the secrets that belongs to the infrastructures
authenticationStrategy: oauth2 # For the time being oauth2 is the only supported
clusterTokenLifespanMinutes: 30 # Postgres token for accessing the database via PAM role
logLevel: info
serviceName: borealis-service
servicePort: 8080
storage: # Storage you want to provision for the borealis infrastructures
  enabled: true # If disabled, you can create your own custom PersistentVolumeClaim, but you MUST specify the name of your claim
  size: 10Gi
  storageClassName: standard
  name: borealis-infrastructures-storage
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
prometheus:
  port: 8428
  imageName: victoriametrics/victoria-metrics
  imageVersion: latest
backup:
  enabled: true
  imageName: chrislusf/seaweedfs
  imageVersion: latest
  port: 8333

operator:
  imageName: public.ecr.aws/borealisdb/operator
  imageVersion: latest
  configMapName: borealis-operator
  replicas: 1
  config:
    api_port: "8085"
    aws_region: eu-central-1
    cluster_domain: cluster.local
    cluster_history_entries: "1000"
    cluster_labels: application:spilo
    cluster_name_label: cluster-name
    docker_image: "registry.opensource.zalan.do/acid/spilo-14:2.1-p3"
    debug_logging: "true"
    enable_ebs_gp3_migration: "false"
    enable_spilo_wal_path_compat: "true"
    external_traffic_policy: "Cluster"
    ready_wait_interval: 3s
    ready_wait_timeout: 30s
    repair_period: 5m
    replication_username: standby
    resource_check_interval: 3s
    resource_check_timeout: 10m
    resync_period: 30m
    ring_log_lines: "100"
    role_deletion_suffix: "_deleted"
    spilo_allow_privilege_escalation: "true"
    spilo_privileged: "false"
    storage_resize_mode: pvc
    super_username: postgres
    watched_namespace: "*"  # listen to all namespaces
    workers: "8"
    major_version_upgrade_mode: manual
    pdb_name_format: "postgres-{cluster}-pdb"
    pod_deletion_wait_timeout: 10m
    pod_label_wait_timeout: 10m
    pod_management_policy: ordered_ready
    pod_role_label: spilo-role
    pod_service_account_name: postgres-pod
    pod_terminate_grace_period: 5m
    spilo_fsgroup: "103"